FROM python:3.9-slim

RUN apt-get update && apt-get install -y unixodbc-dev gcc g++

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

RUN pip3 install flair

COPY flair-ner-rest.py .

CMD [ "python3", "./flair-ner-rest.py" ]
