FROM python:3.6-slim
#FROM python:3.10-slim

RUN apt-get update && apt-get install -y unixodbc-dev gcc g++

RUN pip3 install flair
RUN pip3 install Flask

COPY flair-ner-rest.py .

CMD [ "python3", "./flair-ner-rest.py" ]
